/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/PageLayout/Footer.vue')['default']
    Header: typeof import('./src/components/PageLayout/Header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TContent: typeof import('tdesign-vue-next')['Content']
    TFooter: typeof import('tdesign-vue-next')['Footer']
    THeader: typeof import('tdesign-vue-next')['Header']
    TLayout: typeof import('tdesign-vue-next')['Layout']
    TSpace: typeof import('tdesign-vue-next')['Space']
    TTabs: typeof import('tdesign-vue-next')['Tabs']
  }
}
