/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ParentRouterKey: typeof import('../../../src/types/enums/*.enum').ParentRouterKey
  const UserRole: typeof import('src/types/enums').UserRole
}
